version: '3.7'
networks:
  redpanda_network:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - redpanda_network
    # Mount prometheus configuration
    volumes: [ "./config/prometheus:/etc/prometheus" ]
    ports: 
      - "9090:9090"